"""Typed Streamlit session-state accessors."""
from iad.state.session import (
    KEY_BUSINESS_CASE,
    KEY_DATASET,
    KEY_DATASET_NAME,
    KEY_FEATURE_COLUMNS,
    KEY_MODEL_BUNDLE,
    KEY_PREPROCESSOR,
    KEY_REQUEST_ID,
    KEY_TARGET_COLUMN,
    KEY_TASK_TYPE,
    KEY_TRAINING_REPORT,
    KEY_USER,
    SessionContext,
    init_session_state,
    state_get,
    state_set,
)

__all__ = [
    "SessionContext",
    "KEY_BUSINESS_CASE",
    "KEY_DATASET",
    "KEY_DATASET_NAME",
    "KEY_FEATURE_COLUMNS",
    "KEY_MODEL_BUNDLE",
    "KEY_PREPROCESSOR",
    "KEY_TARGET_COLUMN",
    "KEY_TASK_TYPE",
    "KEY_TRAINING_REPORT",
    "KEY_USER",
    "KEY_REQUEST_ID",
    "init_session_state",
    "state_get",
    "state_set",
]
